version: '2'
services:
  postgres:
    image: postgres
    network_mode: "bridge"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: tokentest

# $DB_PORT wird standardmäßig über das File .env gesetzt.
    ports:
    - "${DB_PORT}:5432"
#  Nutzt eine Ramdisk fuer die Postgres-Daten
    tmpfs:
    - "/var/lib/pgsql/data,mode=777"